# Generated by Django 3.0.3 on 2020-08-03 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200802_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditcard',
            old_name='number',
            new_name='numberCard',
        ),
    ]
