# Generated by Django 3.0.3 on 2020-08-03 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200802_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='numberCard',
            field=models.CharField(max_length=16),
        ),
    ]
