# Generated by Django 3.0.3 on 2020-08-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20200802_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='fk_cardType',
            field=models.CharField(default='VISA', max_length=50),
            preserve_default=False,
        ),
    ]
